"""ML Inference service template."""

from pathlib import Path

from idp_cli.templates.base import BaseTemplate
from idp_cli.utils.file_utils import write_file


class MLInferenceTemplate(BaseTemplate):
    """Generate a production-ready ML inference API service."""

    @property
    def template_name(self) -> str:
        return "ml-inference"

    @property
    def language(self) -> str:
        return "python"

    @property
    def framework(self) -> str:
        return "fastapi"

    def generate_app_code(self) -> None:
        svc = self.service_name
        app_dir = self.service_dir / "app"

        write_file(app_dir / "__init__.py", f'"""ML inference app for {svc}."""\n')

        write_file(
            app_dir / "main.py",
            f'''"""Main FastAPI application for {svc} ML inference service."""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.api.routes import router
from app.core.config import settings
from app.core.health import health_router
from app.ml.model_manager import ModelManager

app = FastAPI(
    title="{svc}",
    description="ML Inference Service - Auto-generated by IDP CLI",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(health_router, tags=["health"])
app.include_router(router, prefix="/api/v1", tags=["inference"])

model_manager = ModelManager()


@app.on_event("startup")
async def startup_event():
    """Load ML models on startup."""
    model_manager.load_models()


@app.on_event("shutdown")
async def shutdown_event():
    """Cleanup on shutdown."""
    model_manager.unload_models()
''',
        )

        write_file(app_dir / "api" / "__init__.py", '"""API package."""\n')

        write_file(
            app_dir / "api" / "routes.py",
            f'''"""Inference API routes for {svc}."""

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Any, Dict, List, Optional

router = APIRouter()


class PredictionRequest(BaseModel):
    """Schema for prediction request."""
    data: Dict[str, Any]
    model_name: Optional[str] = "default"


class PredictionResponse(BaseModel):
    """Schema for prediction response."""
    prediction: Any
    model_name: str
    confidence: Optional[float] = None


@router.post("/predict", response_model=PredictionResponse)
async def predict(request: PredictionRequest):
    """Run model inference."""
    # Placeholder inference logic
    return PredictionResponse(
        prediction={{"result": "placeholder"}},
        model_name=request.model_name,
        confidence=0.95,
    )


@router.get("/models")
async def list_models():
    """List available models."""
    return {{
        "models": [
            {{"name": "default", "version": "1.0", "status": "loaded"}},
        ]
    }}
''',
        )

        write_file(app_dir / "core" / "__init__.py", '"""Core package."""\n')

        write_file(
            app_dir / "core" / "config.py",
            f'''"""Configuration for {svc}."""

from pydantic_settings import BaseSettings
from typing import List


class Settings(BaseSettings):
    APP_NAME: str = "{svc}"
    APP_VERSION: str = "0.1.0"
    DEBUG: bool = False
    HOST: str = "0.0.0.0"
    PORT: int = 8000
    MODEL_PATH: str = "./models"
    ALLOWED_ORIGINS: List[str] = ["*"]

    class Config:
        env_file = ".env"


settings = Settings()
''',
        )

        write_file(
            app_dir / "core" / "health.py",
            f'''"""Health check endpoints."""

from fastapi import APIRouter

health_router = APIRouter()


@health_router.get("/health")
async def health_check():
    return {{"status": "healthy", "service": "{svc}"}}


@health_router.get("/ready")
async def readiness_check():
    return {{"status": "ready", "service": "{svc}"}}
''',
        )

        write_file(app_dir / "ml" / "__init__.py", '"""ML package."""\n')

        write_file(
            app_dir / "ml" / "model_manager.py",
            f'''"""Model manager for loading and serving ML models."""

import logging
from pathlib import Path
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)


class ModelManager:
    """Manages ML model lifecycle - loading, inference, and unloading."""

    def __init__(self, model_dir: str = "./models"):
        self.model_dir = Path(model_dir)
        self.models: Dict[str, Any] = {{}}

    def load_models(self) -> None:
        """Load all models from the model directory."""
        logger.info("Loading models from %s", self.model_dir)
        # Placeholder: load your models here
        self.models["default"] = {{"name": "default", "version": "1.0"}}
        logger.info("Models loaded: %s", list(self.models.keys()))

    def unload_models(self) -> None:
        """Unload all models and free resources."""
        logger.info("Unloading models")
        self.models.clear()

    def predict(self, model_name: str, data: Dict[str, Any]) -> Dict[str, Any]:
        """Run inference using a specified model."""
        if model_name not in self.models:
            raise ValueError(f"Model '{{model_name}}' not found")
        # Placeholder inference
        return {{"prediction": "result", "model": model_name}}

    def get_model_info(self, model_name: str) -> Optional[Dict[str, Any]]:
        """Get information about a loaded model."""
        return self.models.get(model_name)
''',
        )

    def generate_config_files(self) -> None:
        write_file(
            self.service_dir / "requirements.txt",
            """fastapi==0.109.0
uvicorn[standard]==0.27.0
pydantic==2.5.3
pydantic-settings==2.1.0
numpy==1.26.3
scikit-learn==1.4.0
prometheus-client==0.19.0
structlog==24.1.0
python-dotenv==1.0.0
""",
        )

        write_file(
            self.service_dir / "requirements-dev.txt",
            """pytest==7.4.4
pytest-asyncio==0.23.3
pytest-cov==4.1.0
httpx==0.26.0
ruff==0.1.14
mypy==1.8.0
""",
        )

        write_file(
            self.service_dir / ".env.example",
            f"""APP_NAME={self.service_name}
DEBUG=false
HOST=0.0.0.0
PORT=8000
MODEL_PATH=./models
""",
        )

        write_file(
            self.service_dir / ".gitignore",
            """__pycache__/
*.py[cod]
venv/
.venv/
.env
*.log
models/*.pkl
models/*.pt
models/*.onnx
.mypy_cache/
.pytest_cache/
.coverage
""",
        )

        # Create models directory with a placeholder
        write_file(
            self.service_dir / "models" / ".gitkeep",
            "",
        )

    def generate_tests(self) -> None:
        tests_dir = self.service_dir / "tests"
        write_file(tests_dir / "__init__.py", '"""Test package."""\n')

        write_file(
            tests_dir / "conftest.py",
            '''"""Test fixtures."""

import pytest
from fastapi.testclient import TestClient
from app.main import app


@pytest.fixture
def client():
    with TestClient(app) as c:
        yield c
''',
        )

        write_file(
            tests_dir / "test_inference.py",
            '''"""Inference endpoint tests."""


def test_predict(client):
    """Test prediction endpoint."""
    response = client.post(
        "/api/v1/predict",
        json={"data": {"feature": 1.0}},
    )
    assert response.status_code == 200
    data = response.json()
    assert "prediction" in data


def test_list_models(client):
    """Test listing models."""
    response = client.get("/api/v1/models")
    assert response.status_code == 200
    assert "models" in response.json()
''',
        )
