import { BaseTemplate, GeneratedFile, ServiceConfig } from "./base";

export class EventDrivenTemplate extends BaseTemplate {
  get templateName(): string {
    return "event-driven";
  }

  get language(): string {
    return "python";
  }

  get framework(): string {
    return "fastapi";
  }

  generateFiles(): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    const svc = this.getServiceName();
    const svcUnder = this.getServiceNameUnderscore();

    // Main application
    this.addFile(files, "app/__init__.py", `"""${svc} event-driven service."""\n`);

    this.addFile(files, "app/main.py", `"""Main FastAPI application for ${svc}."""

from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.api.routes import router
from app.events.consumer import start_consumer, stop_consumer
from app.core.config import settings


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Manage application lifecycle - start/stop Kafka consumer."""
    await start_consumer()
    yield
    await stop_consumer()


app = FastAPI(
    title="${svc}",
    description="Event-driven service generated by IDP CLI",
    version="0.1.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(router, prefix="/api/v1", tags=["api"])


@app.get("/health")
async def health_check():
    return {"status": "healthy", "service": "${svc}"}
`);

    // API routes
    this.addFile(files, "app/api/__init__.py", `"""API package."""\n`);

    this.addFile(files, "app/api/routes.py", `"""API routes for ${svc}."""

from fastapi import APIRouter, HTTPException
from app.events.producer import publish_event
from app.models.events import EventCreate, EventResponse
from app.events.store import event_store

router = APIRouter()


@router.post("/events", response_model=EventResponse, status_code=201)
async def create_event(event: EventCreate):
    """Publish a new event."""
    published = await publish_event(event)
    return published


@router.get("/events")
async def list_events():
    """List all processed events."""
    return event_store.get_all()


@router.get("/events/{event_id}")
async def get_event(event_id: str):
    """Get event by ID."""
    event = event_store.get(event_id)
    if not event:
        raise HTTPException(status_code=404, detail="Event not found")
    return event
`);

    // Models
    this.addFile(files, "app/models/__init__.py", `"""Models package."""\n`);

    this.addFile(files, "app/models/events.py", `"""Event models for ${svc}."""

from pydantic import BaseModel, Field
from typing import Optional, Any
from datetime import datetime
import uuid


class EventCreate(BaseModel):
    """Schema for creating an event."""
    topic: str = "default"
    event_type: str
    payload: dict[str, Any]


class EventResponse(BaseModel):
    """Schema for event response."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    topic: str
    event_type: str
    payload: dict[str, Any]
    created_at: datetime = Field(default_factory=datetime.utcnow)
    status: str = "published"
`);

    // Events package
    this.addFile(files, "app/events/__init__.py", `"""Events package."""\n`);

    // Producer
    this.addFile(files, "app/events/producer.py", `"""Event producer for ${svc}."""

import json
import uuid
from datetime import datetime
from app.models.events import EventCreate, EventResponse
from app.events.store import event_store
from app.core.config import settings
import logging

logger = logging.getLogger(__name__)


async def publish_event(event: EventCreate) -> EventResponse:
    """Publish an event to the message bus."""
    response = EventResponse(
        id=str(uuid.uuid4()),
        topic=event.topic,
        event_type=event.event_type,
        payload=event.payload,
        created_at=datetime.utcnow(),
        status="published",
    )

    # Store event (event sourcing)
    event_store.append(response)

    logger.info(
        f"Event published: {response.event_type} "
        f"(id={response.id}, topic={response.topic})"
    )

    # In production, publish to Kafka:
    # await kafka_producer.send(event.topic, response.model_dump_json().encode())

    return response
`);

    // Consumer
    this.addFile(files, "app/events/consumer.py", `"""Event consumer for ${svc}."""

import logging

logger = logging.getLogger(__name__)

_running = False


async def start_consumer():
    """Start the event consumer."""
    global _running
    _running = True
    logger.info("Event consumer started")

    # In production, connect to Kafka:
    # consumer = AIOKafkaConsumer(
    #     settings.KAFKA_TOPICS,
    #     bootstrap_servers=settings.KAFKA_BROKERS,
    #     group_id=settings.KAFKA_GROUP_ID,
    # )
    # await consumer.start()


async def stop_consumer():
    """Stop the event consumer."""
    global _running
    _running = False
    logger.info("Event consumer stopped")
`);

    // Event store
    this.addFile(files, "app/events/store.py", `"""In-memory event store for ${svc}."""

from typing import Optional
from app.models.events import EventResponse


class EventStore:
    """Simple in-memory event store (replace with DB in production)."""

    def __init__(self):
        self._events: list[EventResponse] = []

    def append(self, event: EventResponse):
        self._events.append(event)

    def get_all(self) -> list[EventResponse]:
        return list(reversed(self._events))

    def get(self, event_id: str) -> Optional[EventResponse]:
        for event in self._events:
            if event.id == event_id:
                return event
        return None

    def get_by_type(self, event_type: str) -> list[EventResponse]:
        return [e for e in self._events if e.event_type == event_type]


event_store = EventStore()
`);

    // Core config
    this.addFile(files, "app/core/__init__.py", `"""Core package."""\n`);

    this.addFile(files, "app/core/config.py", `"""Configuration for ${svc}."""

from pydantic_settings import BaseSettings
from typing import List


class Settings(BaseSettings):
    APP_NAME: str = "${svc}"
    APP_VERSION: str = "0.1.0"
    PORT: int = ${this.config.port}
    KAFKA_BROKERS: str = "localhost:9092"
    KAFKA_TOPICS: List[str] = ["events"]
    KAFKA_GROUP_ID: str = "${svc}-group"

    class Config:
        env_file = ".env"
        case_sensitive = True


settings = Settings()
`);

    // Requirements
    this.addFile(files, "requirements.txt", `fastapi==0.109.0
uvicorn[standard]==0.27.0
pydantic==2.5.3
pydantic-settings==2.1.0
aiokafka==0.10.0
python-dotenv==1.0.0
structlog==24.1.0
`);

    this.addFile(files, "requirements-dev.txt", `pytest==7.4.4
pytest-asyncio==0.23.3
pytest-cov==4.1.0
httpx==0.26.0
ruff==0.1.14
`);

    this.addFile(files, ".env.example", `APP_NAME=${svc}
PORT=${this.config.port}
KAFKA_BROKERS=localhost:9092
KAFKA_GROUP_ID=${svc}-group
`);

    this.addFile(files, ".gitignore", `__pycache__/
*.py[cod]
.venv/
venv/
.env
*.log
.pytest_cache/
.coverage
`);

    // Tests
    this.addFile(files, "tests/__init__.py", `"""Tests for ${svc}."""\n`);

    this.addFile(files, "tests/conftest.py", `"""Test fixtures."""

import pytest
from fastapi.testclient import TestClient
from app.main import app


@pytest.fixture
def client():
    with TestClient(app) as c:
        yield c
`);

    this.addFile(files, "tests/test_events.py", `"""Event API tests."""


def test_health(client):
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["status"] == "healthy"


def test_publish_event(client):
    response = client.post("/api/v1/events", json={
        "topic": "orders",
        "event_type": "order.created",
        "payload": {"order_id": "123", "amount": 99.99}
    })
    assert response.status_code == 201
    data = response.json()
    assert data["event_type"] == "order.created"
    assert data["status"] == "published"


def test_list_events(client):
    response = client.get("/api/v1/events")
    assert response.status_code == 200
`);

    // Docker
    if (this.config.docker) {
      this.addFile(files, "Dockerfile", `FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE ${this.config.port}
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "${this.config.port}"]
`);

      this.addFile(files, "docker-compose.yml", `version: '3.8'
services:
  ${svc}:
    build: .
    ports:
      - "${this.config.port}:${this.config.port}"
    environment:
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
`);

      this.addFile(files, ".dockerignore", `__pycache__
.venv
.git
.env
tests/
README.md
`);
    }

    // Kubernetes
    if (this.config.k8s) {
      this.addFile(files, "k8s/base/deployment.yaml", `apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${svc}
  labels:
    app: ${svc}
spec:
  replicas: ${this.config.replicas}
  selector:
    matchLabels:
      app: ${svc}
  template:
    metadata:
      labels:
        app: ${svc}
    spec:
      containers:
      - name: ${svc}
        image: ${svc}:latest
        ports:
        - containerPort: ${this.config.port}
        resources:
          requests:
            cpu: ${this.config.resources.cpuRequest}
            memory: ${this.config.resources.memoryRequest}
          limits:
            cpu: ${this.config.resources.cpuLimit}
            memory: ${this.config.resources.memoryLimit}
        env:
        - name: KAFKA_BROKERS
          value: "kafka:9092"
`);

      this.addFile(files, "k8s/base/service.yaml", `apiVersion: v1
kind: Service
metadata:
  name: ${svc}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: ${this.config.port}
  selector:
    app: ${svc}
`);

      this.addFile(files, "k8s/base/kustomization.yaml", `apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  app: ${svc}
`);
    }

    // README
    if (this.config.docs) {
      this.addFile(files, "README.md", `# ${svc}

An event-driven microservice generated by IDP CLI.

## Features

- FastAPI with async event processing
- Kafka producer/consumer (ready to connect)
- Event sourcing with in-memory store
- CQRS-ready architecture
- Docker Compose with Kafka setup

## Getting Started

\`\`\`bash
python -m venv venv
source venv/bin/activate
pip install -r requirements.txt
cp .env.example .env
uvicorn app.main:app --reload --port ${this.config.port}
\`\`\`

## API Endpoints

| Method | Path | Description |
|--------|------|-------------|
| POST | /api/v1/events | Publish an event |
| GET | /api/v1/events | List all events |
| GET | /api/v1/events/{id} | Get event by ID |
| GET | /health | Health check |

## Docker (with Kafka)

\`\`\`bash
docker-compose up -d
\`\`\`

## Testing

\`\`\`bash
pytest
\`\`\`
`);
    }

    return files;
  }
}
