import { BaseTemplate, GeneratedFile, ServiceConfig } from "./base";

export class MLInferenceTemplate extends BaseTemplate {
  get templateName(): string {
    return "ml-inference";
  }

  get language(): string {
    return "python";
  }

  get framework(): string {
    return "fastapi";
  }

  generateFiles(): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    const svc = this.getServiceName();

    this.addFile(files, "app/__init__.py", `"""${svc} ML inference service."""\n`);

    this.addFile(files, "app/main.py", `"""Main FastAPI application for ${svc} ML inference."""

from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.api.routes import router
from app.core.config import settings
from app.ml.model_manager import model_manager


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Load models on startup, cleanup on shutdown."""
    model_manager.load_default_model()
    yield
    model_manager.unload_all()


app = FastAPI(
    title="${svc}",
    description="ML Inference API generated by IDP CLI",
    version="0.1.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(router, prefix="/api/v1", tags=["inference"])


@app.get("/health")
async def health_check():
    return {
        "status": "healthy",
        "service": "${svc}",
        "models_loaded": model_manager.list_models(),
    }


@app.get("/ready")
async def readiness_check():
    is_ready = len(model_manager.list_models()) > 0
    return {"status": "ready" if is_ready else "not ready"}
`);

    // API routes
    this.addFile(files, "app/api/__init__.py", `"""API package."""\n`);

    this.addFile(files, "app/api/routes.py", `"""ML inference API routes for ${svc}."""

from fastapi import APIRouter, HTTPException
from typing import List
from app.models.schemas import (
    PredictionRequest,
    PredictionResponse,
    BatchPredictionRequest,
    BatchPredictionResponse,
    ModelInfo,
)
from app.ml.model_manager import model_manager

router = APIRouter()


@router.post("/predict", response_model=PredictionResponse)
async def predict(request: PredictionRequest):
    """Run inference on a single input."""
    model = model_manager.get_model(request.model_name)
    if not model:
        raise HTTPException(status_code=404, detail=f"Model '{request.model_name}' not found")

    result = model.predict(request.input_data)
    return PredictionResponse(
        model_name=request.model_name,
        model_version=model.version,
        prediction=result["prediction"],
        confidence=result.get("confidence"),
    )


@router.post("/predict/batch", response_model=BatchPredictionResponse)
async def batch_predict(request: BatchPredictionRequest):
    """Run inference on a batch of inputs."""
    model = model_manager.get_model(request.model_name)
    if not model:
        raise HTTPException(status_code=404, detail=f"Model '{request.model_name}' not found")

    results = [model.predict(inp) for inp in request.inputs]
    return BatchPredictionResponse(
        model_name=request.model_name,
        model_version=model.version,
        predictions=[r["prediction"] for r in results],
        count=len(results),
    )


@router.get("/models", response_model=List[ModelInfo])
async def list_models():
    """List all loaded models."""
    return [
        ModelInfo(name=name, version=m.version, status="loaded")
        for name, m in model_manager.models.items()
    ]


@router.post("/models/{model_name}/load")
async def load_model(model_name: str):
    """Load a model by name."""
    model_manager.load_model(model_name)
    return {"status": "loaded", "model": model_name}


@router.post("/models/{model_name}/unload")
async def unload_model(model_name: str):
    """Unload a model by name."""
    model_manager.unload_model(model_name)
    return {"status": "unloaded", "model": model_name}
`);

    // Models/schemas
    this.addFile(files, "app/models/__init__.py", `"""Models package."""\n`);

    this.addFile(files, "app/models/schemas.py", `"""Request/response schemas for ${svc}."""

from pydantic import BaseModel
from typing import Any, Optional, List


class PredictionRequest(BaseModel):
    model_name: str = "default"
    input_data: dict[str, Any]


class PredictionResponse(BaseModel):
    model_name: str
    model_version: str
    prediction: Any
    confidence: Optional[float] = None


class BatchPredictionRequest(BaseModel):
    model_name: str = "default"
    inputs: List[dict[str, Any]]


class BatchPredictionResponse(BaseModel):
    model_name: str
    model_version: str
    predictions: List[Any]
    count: int


class ModelInfo(BaseModel):
    name: str
    version: str
    status: str
`);

    // ML package
    this.addFile(files, "app/ml/__init__.py", `"""ML package."""\n`);

    this.addFile(files, "app/ml/base_model.py", `"""Base model interface for ${svc}."""

from abc import ABC, abstractmethod
from typing import Any


class BaseMLModel(ABC):
    """Abstract base class for ML models."""

    def __init__(self, name: str, version: str = "1.0.0"):
        self.name = name
        self.version = version

    @abstractmethod
    def load(self) -> None:
        """Load the model."""
        pass

    @abstractmethod
    def predict(self, input_data: dict[str, Any]) -> dict[str, Any]:
        """Run prediction on input data."""
        pass

    @abstractmethod
    def unload(self) -> None:
        """Unload the model and free resources."""
        pass
`);

    this.addFile(files, "app/ml/demo_model.py", `"""Demo model for ${svc} (replace with real model)."""

import random
from typing import Any
from app.ml.base_model import BaseMLModel


class DemoModel(BaseMLModel):
    """A demo model that returns random predictions."""

    def __init__(self):
        super().__init__(name="default", version="1.0.0")
        self._loaded = False

    def load(self) -> None:
        """Simulate loading a model."""
        self._loaded = True

    def predict(self, input_data: dict[str, Any]) -> dict[str, Any]:
        """Return a demo prediction."""
        if not self._loaded:
            raise RuntimeError("Model not loaded")

        # Replace this with actual model inference
        prediction = random.choice(["class_a", "class_b", "class_c"])
        confidence = round(random.uniform(0.7, 0.99), 4)

        return {
            "prediction": prediction,
            "confidence": confidence,
            "input_features": list(input_data.keys()),
        }

    def unload(self) -> None:
        """Unload the model."""
        self._loaded = False
`);

    this.addFile(files, "app/ml/model_manager.py", `"""Model manager for ${svc}."""

import logging
from typing import Optional
from app.ml.base_model import BaseMLModel
from app.ml.demo_model import DemoModel

logger = logging.getLogger(__name__)


class ModelManager:
    """Manages loading and serving ML models."""

    def __init__(self):
        self.models: dict[str, BaseMLModel] = {}

    def load_default_model(self):
        """Load the default demo model."""
        self.load_model("default")

    def load_model(self, name: str):
        """Load a model by name."""
        if name in self.models:
            logger.info(f"Model '{name}' already loaded")
            return

        # Add model registry here for different model types
        model = DemoModel()
        model.load()
        self.models[name] = model
        logger.info(f"Model '{name}' loaded (v{model.version})")

    def get_model(self, name: str) -> Optional[BaseMLModel]:
        """Get a loaded model by name."""
        return self.models.get(name)

    def unload_model(self, name: str):
        """Unload a model."""
        if name in self.models:
            self.models[name].unload()
            del self.models[name]
            logger.info(f"Model '{name}' unloaded")

    def unload_all(self):
        """Unload all models."""
        for name in list(self.models.keys()):
            self.unload_model(name)

    def list_models(self) -> list[str]:
        return list(self.models.keys())


model_manager = ModelManager()
`);

    // Core config
    this.addFile(files, "app/core/__init__.py", `"""Core package."""\n`);

    this.addFile(files, "app/core/config.py", `"""Configuration for ${svc}."""

from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    APP_NAME: str = "${svc}"
    APP_VERSION: str = "0.1.0"
    PORT: int = ${this.config.port}
    MODEL_PATH: str = "./models"
    DEFAULT_MODEL: str = "default"

    class Config:
        env_file = ".env"
        case_sensitive = True


settings = Settings()
`);

    this.addFile(files, "requirements.txt", `fastapi==0.109.0
uvicorn[standard]==0.27.0
pydantic==2.5.3
pydantic-settings==2.1.0
python-dotenv==1.0.0
numpy==1.26.3
scikit-learn==1.4.0
prometheus-client==0.19.0
`);

    this.addFile(files, "requirements-dev.txt", `pytest==7.4.4
pytest-asyncio==0.23.3
httpx==0.26.0
ruff==0.1.14
`);

    this.addFile(files, ".env.example", `APP_NAME=${svc}
PORT=${this.config.port}
MODEL_PATH=./models
`);

    this.addFile(files, ".gitignore", `__pycache__/
*.py[cod]
.venv/
venv/
.env
*.log
.pytest_cache/
.coverage
models/*.pkl
models/*.pt
models/*.onnx
`);

    this.addFile(files, "models/.gitkeep", ``);

    // Tests
    this.addFile(files, "tests/__init__.py", `"""Tests."""\n`);

    this.addFile(files, "tests/conftest.py", `"""Test fixtures."""

import pytest
from fastapi.testclient import TestClient
from app.main import app


@pytest.fixture
def client():
    with TestClient(app) as c:
        yield c
`);

    this.addFile(files, "tests/test_inference.py", `"""Inference API tests."""


def test_health(client):
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["status"] == "healthy"


def test_predict(client):
    response = client.post("/api/v1/predict", json={
        "model_name": "default",
        "input_data": {"feature1": 1.0, "feature2": 2.0}
    })
    assert response.status_code == 200
    data = response.json()
    assert "prediction" in data
    assert "confidence" in data


def test_batch_predict(client):
    response = client.post("/api/v1/predict/batch", json={
        "model_name": "default",
        "inputs": [
            {"feature1": 1.0},
            {"feature1": 2.0},
        ]
    })
    assert response.status_code == 200
    assert response.json()["count"] == 2


def test_list_models(client):
    response = client.get("/api/v1/models")
    assert response.status_code == 200
`);

    // Docker
    if (this.config.docker) {
      this.addFile(files, "Dockerfile", `FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN mkdir -p models
EXPOSE ${this.config.port}
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "${this.config.port}"]
`);

      this.addFile(files, ".dockerignore", `__pycache__
.venv
.git
.env
tests/
README.md
`);
    }

    // Kubernetes
    if (this.config.k8s) {
      this.addFile(files, "k8s/base/deployment.yaml", `apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${svc}
  labels:
    app: ${svc}
spec:
  replicas: ${this.config.replicas}
  selector:
    matchLabels:
      app: ${svc}
  template:
    metadata:
      labels:
        app: ${svc}
    spec:
      containers:
      - name: ${svc}
        image: ${svc}:latest
        ports:
        - containerPort: ${this.config.port}
        resources:
          requests:
            cpu: ${this.config.resources.cpuRequest}
            memory: ${this.config.resources.memoryRequest}
          limits:
            cpu: ${this.config.resources.cpuLimit}
            memory: ${this.config.resources.memoryLimit}
        livenessProbe:
          httpGet:
            path: /health
            port: ${this.config.port}
          initialDelaySeconds: 30
          periodSeconds: 10
`);

      this.addFile(files, "k8s/base/service.yaml", `apiVersion: v1
kind: Service
metadata:
  name: ${svc}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: ${this.config.port}
  selector:
    app: ${svc}
`);

      this.addFile(files, "k8s/base/kustomization.yaml", `apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  app: ${svc}
`);
    }

    // README
    if (this.config.docs) {
      this.addFile(files, "README.md", `# ${svc}

An ML inference API service generated by IDP CLI.

## Features

- FastAPI with async model serving
- Model versioning and hot-loading
- Single and batch prediction endpoints
- Model manager with load/unload lifecycle
- Pluggable model architecture

## Getting Started

\`\`\`bash
python -m venv venv
source venv/bin/activate
pip install -r requirements.txt
uvicorn app.main:app --reload --port ${this.config.port}
\`\`\`

## Endpoints

| Method | Path | Description |
|--------|------|-------------|
| POST | /api/v1/predict | Single prediction |
| POST | /api/v1/predict/batch | Batch prediction |
| GET | /api/v1/models | List loaded models |
| POST | /api/v1/models/{name}/load | Load a model |
| POST | /api/v1/models/{name}/unload | Unload a model |
| GET | /health | Health check |

## Docker

\`\`\`bash
docker build -t ${svc} .
docker run -p ${this.config.port}:${this.config.port} ${svc}
\`\`\`
`);
    }

    return files;
  }
}
