import { BaseTemplate, GeneratedFile, ServiceConfig } from "./base";

export class NextjsFullstackTemplate extends BaseTemplate {
  get templateName(): string {
    return "nextjs-fullstack";
  }

  get language(): string {
    return "typescript";
  }

  get framework(): string {
    return "nextjs";
  }

  generateFiles(): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    const svc = this.getServiceName();

    // package.json
    this.addFile(files, "package.json", `{
  "name": "${svc}",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev --port ${this.config.port}",
    "build": "next build",
    "start": "next start --port ${this.config.port}",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "14.1.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "typescript": "^5",
    "tailwindcss": "^3.4.1",
    "postcss": "^8",
    "autoprefixer": "^10"
  }
}
`);

    // next.config.js
    this.addFile(files, "next.config.js", `/** @type {import('next').NextConfig} */
const nextConfig = {}

module.exports = nextConfig
`);

    // tsconfig.json
    this.addFile(files, "tsconfig.json", `{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`);

    // tailwind.config.ts
    this.addFile(files, "tailwind.config.ts", `import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
export default config
`);

    // postcss.config.js
    this.addFile(files, "postcss.config.js", `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`);

    // src/app/layout.tsx
    this.addFile(files, "src/app/layout.tsx", `import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: '${svc}',
  description: 'Full-stack Next.js application generated by IDP CLI',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav className="bg-gray-900 text-white">
          <div className="max-w-6xl mx-auto px-4 py-3 flex justify-between items-center">
            <a href="/" className="text-lg font-bold">${svc}</a>
            <div className="flex gap-4 text-sm">
              <a href="/" className="hover:text-blue-400 transition">Home</a>
              <a href="/about" className="hover:text-blue-400 transition">About</a>
              <a href="/api/hello" className="hover:text-blue-400 transition">API</a>
            </div>
          </div>
        </nav>
        <main className="max-w-6xl mx-auto px-4 py-8">
          {children}
        </main>
      </body>
    </html>
  )
}
`);

    // src/app/globals.css
    this.addFile(files, "src/app/globals.css", `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}
`);

    // src/app/page.tsx
    this.addFile(files, "src/app/page.tsx", `export default function Home() {
  return (
    <div className="text-center mt-12">
      <h1 className="text-4xl font-bold mb-4">Welcome to ${svc}</h1>
      <p className="text-gray-600 mb-8">
        A full-stack Next.js 14 application generated by IDP CLI.
      </p>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-8">
        <Card
          title="App Router"
          description="Built with Next.js 14 App Router and Server Components."
        />
        <Card
          title="API Routes"
          description="Built-in API routes for your backend logic."
        />
        <Card
          title="Tailwind CSS"
          description="Styled with Tailwind CSS for rapid UI development."
        />
      </div>
    </div>
  )
}

function Card({ title, description }: { title: string; description: string }) {
  return (
    <div className="border rounded-lg p-6 hover:border-blue-500 transition">
      <h3 className="text-lg font-semibold mb-2">{title}</h3>
      <p className="text-gray-500 text-sm">{description}</p>
    </div>
  )
}
`);

    // src/app/about/page.tsx
    this.addFile(files, "src/app/about/page.tsx", `export default function About() {
  return (
    <div className="max-w-2xl mx-auto mt-8">
      <h1 className="text-3xl font-bold mb-4">About ${svc}</h1>
      <p className="text-gray-600 mb-4">
        This application was generated using the Internal Developer Platform CLI.
      </p>
      <ul className="list-disc pl-6 space-y-2 text-gray-600">
        <li>Next.js 14 with App Router</li>
        <li>TypeScript for type safety</li>
        <li>Tailwind CSS for styling</li>
        <li>API Routes for backend</li>
        <li>Server Components by default</li>
      </ul>
    </div>
  )
}
`);

    // API route
    this.addFile(files, "src/app/api/hello/route.ts", `import { NextResponse } from 'next/server'

export async function GET() {
  return NextResponse.json({
    message: 'Hello from ${svc} API!',
    timestamp: new Date().toISOString(),
  })
}

export async function POST(request: Request) {
  const body = await request.json()
  return NextResponse.json({
    message: 'Received data',
    data: body,
  }, { status: 201 })
}
`);

    // API health
    this.addFile(files, "src/app/api/health/route.ts", `import { NextResponse } from 'next/server'

export async function GET() {
  return NextResponse.json({
    status: 'healthy',
    service: '${svc}',
    timestamp: new Date().toISOString(),
  })
}
`);

    this.addFile(files, ".gitignore", `.next/
node_modules/
out/
.env
*.log
.DS_Store
`);

    // Docker
    if (this.config.docker) {
      this.addFile(files, "Dockerfile", `FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV production
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE ${this.config.port}
ENV PORT ${this.config.port}
CMD ["node", "server.js"]
`);

      this.addFile(files, ".dockerignore", `.next/
node_modules/
.git
README.md
`);
    }

    // Kubernetes
    if (this.config.k8s) {
      this.addFile(files, "k8s/base/deployment.yaml", `apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${svc}
  labels:
    app: ${svc}
spec:
  replicas: ${this.config.replicas}
  selector:
    matchLabels:
      app: ${svc}
  template:
    metadata:
      labels:
        app: ${svc}
    spec:
      containers:
      - name: ${svc}
        image: ${svc}:latest
        ports:
        - containerPort: ${this.config.port}
        resources:
          requests:
            cpu: ${this.config.resources.cpuRequest}
            memory: ${this.config.resources.memoryRequest}
          limits:
            cpu: ${this.config.resources.cpuLimit}
            memory: ${this.config.resources.memoryLimit}
        livenessProbe:
          httpGet:
            path: /api/health
            port: ${this.config.port}
          initialDelaySeconds: 10
          periodSeconds: 10
`);

      this.addFile(files, "k8s/base/service.yaml", `apiVersion: v1
kind: Service
metadata:
  name: ${svc}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: ${this.config.port}
  selector:
    app: ${svc}
`);

      this.addFile(files, "k8s/base/kustomization.yaml", `apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  app: ${svc}
`);
    }

    // README
    if (this.config.docs) {
      this.addFile(files, "README.md", `# ${svc}

A full-stack Next.js 14 application generated by IDP CLI.

## Features

- Next.js 14 with App Router
- TypeScript
- Tailwind CSS
- API Routes
- Server Components

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

App: http://localhost:${this.config.port}

## API Endpoints

- GET /api/hello - Hello endpoint
- POST /api/hello - Echo endpoint
- GET /api/health - Health check

## Docker

\`\`\`bash
docker build -t ${svc} .
docker run -p ${this.config.port}:${this.config.port} ${svc}
\`\`\`
`);
    }

    return files;
  }
}
