import { BaseTemplate, GeneratedFile, ServiceConfig } from "./base";

export class PythonCLITemplate extends BaseTemplate {
  get templateName(): string {
    return "python-cli";
  }

  get language(): string {
    return "python";
  }

  get framework(): string {
    return "click";
  }

  generateFiles(): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    const svc = this.getServiceName();
    const svcUnder = this.getServiceNameUnderscore();

    // pyproject.toml
    this.addFile(files, "pyproject.toml", `[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "${svc}"
version = "0.1.0"
description = "CLI tool generated by IDP CLI"
requires-python = ">=3.9"
dependencies = [
    "click>=8.1.7",
    "rich>=13.7.0",
    "pydantic>=2.5.3",
    "pydantic-settings>=2.1.0",
    "python-dotenv>=1.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.4",
    "pytest-cov>=4.1.0",
    "ruff>=0.1.14",
    "mypy>=1.8.0",
]

[project.scripts]
${svc} = "${svcUnder}.cli:main"

[tool.ruff]
target-version = "py39"
line-length = 88
`);

    // Package init
    this.addFile(files, `${svcUnder}/__init__.py`, `"""${svc} - CLI tool generated by IDP CLI."""

__version__ = "0.1.0"
`);

    // CLI entry
    this.addFile(files, `${svcUnder}/cli.py`, `"""Main CLI entry point for ${svc}."""

import click
from rich.console import Console
from rich.table import Table
from rich.panel import Panel

from ${svcUnder}.config import settings
from ${svcUnder}.commands import init, run, status

console = Console()


@click.group()
@click.version_option(version="0.1.0", prog_name="${svc}")
@click.option("--verbose", "-v", is_flag=True, help="Enable verbose output")
@click.pass_context
def main(ctx, verbose):
    """${svc} - A CLI tool generated by IDP CLI."""
    ctx.ensure_object(dict)
    ctx.obj["verbose"] = verbose
    ctx.obj["console"] = console


@main.command()
@click.argument("name")
@click.option("--template", "-t", default="default", help="Template to use")
@click.pass_context
def init(ctx, name, template):
    """Initialize a new project."""
    console = ctx.obj["console"]
    console.print(Panel(f"[bold green]Initializing project: {name}[/]"))
    console.print(f"  Template: [cyan]{template}[/]")
    console.print(f"  Location: [cyan]./{name}/[/]")
    console.print("[green]✓ Project initialized successfully![/]")


@main.command()
@click.option("--config", "-c", default=None, help="Config file path")
@click.option("--dry-run", is_flag=True, help="Run without making changes")
@click.pass_context
def run(ctx, config, dry_run):
    """Run the main task."""
    console = ctx.obj["console"]
    verbose = ctx.obj["verbose"]

    if dry_run:
        console.print("[yellow]Running in dry-run mode[/]")

    console.print(Panel("[bold]Running task...[/]"))

    # Add your main logic here
    steps = ["Validating config", "Processing data", "Generating output", "Cleanup"]
    for step in steps:
        if verbose:
            console.print(f"  [dim]→ {step}[/]")
        console.print(f"  [green]✓[/] {step}")

    console.print("\\n[bold green]✓ Task completed successfully![/]")


@main.command()
@click.pass_context
def status(ctx):
    """Show current status."""
    console = ctx.obj["console"]

    table = Table(title="${svc} Status")
    table.add_column("Property", style="cyan")
    table.add_column("Value", style="green")

    table.add_row("Version", "0.1.0")
    table.add_row("App Name", settings.APP_NAME)
    table.add_row("Log Level", settings.LOG_LEVEL)
    table.add_row("Config File", settings.CONFIG_FILE or "None")

    console.print(table)


@main.command()
@click.pass_context
def config(ctx):
    """Show configuration."""
    console = ctx.obj["console"]
    console.print(Panel("[bold]Current Configuration[/]"))
    console.print(f"  APP_NAME: [cyan]{settings.APP_NAME}[/]")
    console.print(f"  LOG_LEVEL: [cyan]{settings.LOG_LEVEL}[/]")
    console.print(f"  CONFIG_FILE: [cyan]{settings.CONFIG_FILE or 'None'}[/]")


if __name__ == "__main__":
    main()
`);

    // Config
    this.addFile(files, `${svcUnder}/config.py`, `"""Configuration for ${svc}."""

from pydantic_settings import BaseSettings
from typing import Optional


class Settings(BaseSettings):
    APP_NAME: str = "${svc}"
    LOG_LEVEL: str = "info"
    CONFIG_FILE: Optional[str] = None
    DEBUG: bool = False

    class Config:
        env_file = ".env"
        env_prefix = "${svcUnder.toUpperCase()}_"
        case_sensitive = True


settings = Settings()
`);

    // Commands package
    this.addFile(files, `${svcUnder}/commands/__init__.py`, `"""CLI commands package."""

from ${svcUnder}.commands.init import init
from ${svcUnder}.commands.run import run
from ${svcUnder}.commands.status import status

__all__ = ["init", "run", "status"]
`);

    this.addFile(files, `${svcUnder}/commands/init.py`, `"""Init command."""


def init(name: str, template: str = "default"):
    """Initialize a new project."""
    pass
`);

    this.addFile(files, `${svcUnder}/commands/run.py`, `"""Run command."""


def run(config=None, dry_run=False):
    """Run the main task."""
    pass
`);

    this.addFile(files, `${svcUnder}/commands/status.py`, `"""Status command."""


def status():
    """Show current status."""
    pass
`);

    // Utils
    this.addFile(files, `${svcUnder}/utils.py`, `"""Utility functions for ${svc}."""

import logging
import sys


def get_logger(name: str, level: str = "info") -> logging.Logger:
    """Create a configured logger."""
    logger = logging.getLogger(name)
    logger.setLevel(getattr(logging, level.upper(), logging.INFO))

    if not logger.handlers:
        handler = logging.StreamHandler(sys.stderr)
        fmt = logging.Formatter("%(asctime)s [%(levelname)s] %(message)s")
        handler.setFormatter(fmt)
        logger.addHandler(handler)

    return logger
`);

    this.addFile(files, "requirements.txt", `click>=8.1.7
rich>=13.7.0
pydantic>=2.5.3
pydantic-settings>=2.1.0
python-dotenv>=1.0.0
`);

    this.addFile(files, "requirements-dev.txt", `pytest>=7.4.4
pytest-cov>=4.1.0
ruff>=0.1.14
mypy>=1.8.0
`);

    this.addFile(files, ".env.example", `${svcUnder.toUpperCase()}_APP_NAME=${svc}
${svcUnder.toUpperCase()}_LOG_LEVEL=info
`);

    this.addFile(files, ".gitignore", `__pycache__/
*.py[cod]
*.egg-info/
dist/
build/
.venv/
venv/
.env
*.log
.pytest_cache/
.coverage
.mypy_cache/
`);

    // Tests
    this.addFile(files, "tests/__init__.py", `"""Tests for ${svc}."""\n`);

    this.addFile(files, "tests/test_cli.py", `"""CLI tests for ${svc}."""

from click.testing import CliRunner
from ${svcUnder}.cli import main


runner = CliRunner()


def test_version():
    result = runner.invoke(main, ["--version"])
    assert result.exit_code == 0
    assert "0.1.0" in result.output


def test_status():
    result = runner.invoke(main, ["status"])
    assert result.exit_code == 0


def test_config():
    result = runner.invoke(main, ["config"])
    assert result.exit_code == 0


def test_init():
    result = runner.invoke(main, ["init", "test-project"])
    assert result.exit_code == 0
    assert "test-project" in result.output


def test_run():
    result = runner.invoke(main, ["run"])
    assert result.exit_code == 0
    assert "completed" in result.output


def test_run_dry():
    result = runner.invoke(main, ["run", "--dry-run"])
    assert result.exit_code == 0
    assert "dry-run" in result.output
`);

    // Docker
    if (this.config.docker) {
      this.addFile(files, "Dockerfile", `FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN pip install -e .
ENTRYPOINT ["${svc}"]
`);

      this.addFile(files, ".dockerignore", `__pycache__
.venv
.git
.env
tests/
README.md
`);
    }

    // README
    if (this.config.docs) {
      this.addFile(files, "README.md", `# ${svc}

A command-line tool with Click and Rich, generated by IDP CLI.

## Features

- Click CLI framework with sub-commands
- Rich terminal UI with tables and panels
- Pydantic configuration management
- Modular command structure

## Installation

\`\`\`bash
python -m venv venv
source venv/bin/activate
pip install -e .
\`\`\`

## Usage

\`\`\`bash
# Show help
${svc} --help

# Initialize a project
${svc} init my-project --template default

# Run main task
${svc} run
${svc} run --dry-run
${svc} run --verbose

# Show status
${svc} status

# Show config
${svc} config
\`\`\`

## Testing

\`\`\`bash
pip install -e ".[dev]"
pytest
\`\`\`

## Docker

\`\`\`bash
docker build -t ${svc} .
docker run ${svc} --help
\`\`\`
`);
    }

    return files;
  }
}
