import { BaseTemplate, GeneratedFile, ServiceConfig } from "./base";

export class PythonGraphQLTemplate extends BaseTemplate {
  get templateName(): string {
    return "python-graphql";
  }

  get language(): string {
    return "python";
  }

  get framework(): string {
    return "strawberry";
  }

  generateFiles(): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    const svc = this.getServiceName();

    this.addFile(files, "app/__init__.py", `"""${svc} GraphQL service."""\n`);

    this.addFile(files, "app/main.py", `"""Main FastAPI + Strawberry GraphQL application for ${svc}."""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import strawberry
from strawberry.fastapi import GraphQLRouter

from app.schema.query import Query
from app.schema.mutation import Mutation
from app.schema.subscription import Subscription

schema = strawberry.Schema(
    query=Query,
    mutation=Mutation,
    subscription=Subscription,
)

graphql_app = GraphQLRouter(schema)

app = FastAPI(
    title="${svc}",
    description="GraphQL API generated by IDP CLI",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(graphql_app, prefix="/graphql")


@app.get("/health")
async def health_check():
    return {"status": "healthy", "service": "${svc}"}
`);

    // Schema
    this.addFile(files, "app/schema/__init__.py", `"""GraphQL schema package."""\n`);

    this.addFile(files, "app/schema/types.py", `"""GraphQL types for ${svc}."""

import strawberry
from typing import Optional


@strawberry.type
class Item:
    id: int
    name: str
    description: Optional[str] = None


@strawberry.input
class CreateItemInput:
    name: str
    description: Optional[str] = None


@strawberry.input
class UpdateItemInput:
    name: Optional[str] = None
    description: Optional[str] = None
`);

    this.addFile(files, "app/schema/query.py", `"""GraphQL queries for ${svc}."""

import strawberry
from typing import List, Optional
from app.schema.types import Item
from app.data.store import item_store


@strawberry.type
class Query:
    @strawberry.field
    def items(self) -> List[Item]:
        """Get all items."""
        return [Item(**i) for i in item_store.get_all()]

    @strawberry.field
    def item(self, id: int) -> Optional[Item]:
        """Get an item by ID."""
        data = item_store.get(id)
        return Item(**data) if data else None

    @strawberry.field
    def items_count(self) -> int:
        """Get total items count."""
        return len(item_store.get_all())
`);

    this.addFile(files, "app/schema/mutation.py", `"""GraphQL mutations for ${svc}."""

import strawberry
from app.schema.types import Item, CreateItemInput, UpdateItemInput
from app.data.store import item_store


@strawberry.type
class Mutation:
    @strawberry.mutation
    def create_item(self, input: CreateItemInput) -> Item:
        """Create a new item."""
        data = item_store.create(input.name, input.description)
        return Item(**data)

    @strawberry.mutation
    def update_item(self, id: int, input: UpdateItemInput) -> Item:
        """Update an existing item."""
        data = item_store.update(id, input.name, input.description)
        if not data:
            raise ValueError(f"Item {id} not found")
        return Item(**data)

    @strawberry.mutation
    def delete_item(self, id: int) -> bool:
        """Delete an item."""
        return item_store.delete(id)
`);

    this.addFile(files, "app/schema/subscription.py", `"""GraphQL subscriptions for ${svc}."""

import strawberry
import asyncio
from typing import AsyncGenerator
from app.schema.types import Item


@strawberry.type
class Subscription:
    @strawberry.subscription
    async def item_added(self) -> AsyncGenerator[str, None]:
        """Subscribe to item creation events."""
        while True:
            yield "Waiting for new items..."
            await asyncio.sleep(5)
`);

    // Data store
    this.addFile(files, "app/data/__init__.py", `"""Data package."""\n`);

    this.addFile(files, "app/data/store.py", `"""In-memory data store for ${svc}."""

from typing import Optional
import threading


class ItemStore:
    def __init__(self):
        self._items: list[dict] = []
        self._counter = 0
        self._lock = threading.Lock()

    def get_all(self) -> list[dict]:
        return list(self._items)

    def get(self, item_id: int) -> Optional[dict]:
        for item in self._items:
            if item["id"] == item_id:
                return item
        return None

    def create(self, name: str, description: Optional[str] = None) -> dict:
        with self._lock:
            self._counter += 1
            item = {"id": self._counter, "name": name, "description": description}
            self._items.append(item)
            return item

    def update(self, item_id: int, name: Optional[str], description: Optional[str]) -> Optional[dict]:
        for item in self._items:
            if item["id"] == item_id:
                if name is not None:
                    item["name"] = name
                if description is not None:
                    item["description"] = description
                return item
        return None

    def delete(self, item_id: int) -> bool:
        with self._lock:
            for i, item in enumerate(self._items):
                if item["id"] == item_id:
                    self._items.pop(i)
                    return True
            return False


item_store = ItemStore()
`);

    this.addFile(files, "requirements.txt", `fastapi==0.109.0
uvicorn[standard]==0.27.0
strawberry-graphql[fastapi]==0.217.0
pydantic==2.5.3
python-dotenv==1.0.0
`);

    this.addFile(files, "requirements-dev.txt", `pytest==7.4.4
pytest-asyncio==0.23.3
httpx==0.26.0
ruff==0.1.14
`);

    this.addFile(files, ".env.example", `APP_NAME=${svc}
PORT=${this.config.port}
`);

    this.addFile(files, ".gitignore", `__pycache__/
*.py[cod]
.venv/
venv/
.env
*.log
.pytest_cache/
.coverage
`);

    // Tests
    this.addFile(files, "tests/__init__.py", `"""Tests for ${svc}."""\n`);

    this.addFile(files, "tests/conftest.py", `"""Test fixtures."""

import pytest
from fastapi.testclient import TestClient
from app.main import app


@pytest.fixture
def client():
    with TestClient(app) as c:
        yield c
`);

    this.addFile(files, "tests/test_graphql.py", `"""GraphQL endpoint tests."""


def test_health(client):
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["status"] == "healthy"


def test_query_items(client):
    response = client.post("/graphql", json={
        "query": "{ items { id name } }"
    })
    assert response.status_code == 200


def test_create_item(client):
    response = client.post("/graphql", json={
        "query": 'mutation { createItem(input: { name: "Test" }) { id name } }'
    })
    assert response.status_code == 200
`);

    // Docker
    if (this.config.docker) {
      this.addFile(files, "Dockerfile", `FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE ${this.config.port}
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "${this.config.port}"]
`);

      this.addFile(files, ".dockerignore", `__pycache__
.venv
.git
.env
tests/
README.md
`);
    }

    // Kubernetes
    if (this.config.k8s) {
      this.addFile(files, "k8s/base/deployment.yaml", `apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${svc}
  labels:
    app: ${svc}
spec:
  replicas: ${this.config.replicas}
  selector:
    matchLabels:
      app: ${svc}
  template:
    metadata:
      labels:
        app: ${svc}
    spec:
      containers:
      - name: ${svc}
        image: ${svc}:latest
        ports:
        - containerPort: ${this.config.port}
        resources:
          requests:
            cpu: ${this.config.resources.cpuRequest}
            memory: ${this.config.resources.memoryRequest}
          limits:
            cpu: ${this.config.resources.cpuLimit}
            memory: ${this.config.resources.memoryLimit}
`);

      this.addFile(files, "k8s/base/service.yaml", `apiVersion: v1
kind: Service
metadata:
  name: ${svc}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: ${this.config.port}
  selector:
    app: ${svc}
`);

      this.addFile(files, "k8s/base/kustomization.yaml", `apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  app: ${svc}
`);
    }

    // README
    if (this.config.docs) {
      this.addFile(files, "README.md", `# ${svc}

A Python GraphQL API using Strawberry with FastAPI, generated by IDP CLI.

## Features

- Strawberry GraphQL with type safety
- FastAPI integration
- Queries, Mutations, and Subscriptions
- DataLoader-ready architecture
- GraphQL Playground at /graphql

## Getting Started

\`\`\`bash
python -m venv venv
source venv/bin/activate
pip install -r requirements.txt
uvicorn app.main:app --reload --port ${this.config.port}
\`\`\`

- GraphQL Playground: http://localhost:${this.config.port}/graphql
- Health Check: http://localhost:${this.config.port}/health

## Example Queries

\`\`\`graphql
# List items
query {
  items { id name description }
}

# Create item
mutation {
  createItem(input: { name: "My Item", description: "A test item" }) {
    id name
  }
}
\`\`\`

## Docker

\`\`\`bash
docker build -t ${svc} .
docker run -p ${this.config.port}:${this.config.port} ${svc}
\`\`\`
`);
    }

    return files;
  }
}
